### ISSUE TITLE
build-and-run-tests.py: Missing positional argument in call to install_llvm_tool 

### ISSUE THREAD

**Issue by masinag** [RosettaCommons/binder#266]
Hi,
I get the following error when running `./build-and-run-tests.py`:
```Traceback (most recent call last):
  File "binder/./build-and-run-tests.py", line 53, in <module>
    main(sys.argv)
  File "binder/./build-and-run-tests.py", line 45, in main
    if not Options.binder: Options.binder = build.install_llvm_tool('binder', source_path+'/source', source_path + '/build', Options.binder_debug, jobs=Options.jobs, gcc_install_prefix=Options.gcc_install_prefix)
TypeError: install_llvm_tool() missing 1 required positional argument: 'compiler'
```

**Comment by lyskov** [comment]
Thank you for letting us know and for the fix!
